USE [TraficDB]
GO
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DimCity](
	[City_Key] [int] IDENTITY(1,1) NOT NULL,
	[Record_id] [int] NOT NULL,
	[Date] [date] NOT NULL,
	[Hour] [int] NOT NULL,
	[Road_name] [nvarchar](50) NOT NULL,
	[City] [nvarchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[City_Key] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


